project:
  type: website
  output-dir: docs

website:
  title: "edmolo.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: bluesky
        href: https://bsky.app/profile/edmolo.bsky.social
      - icon: github
        href: https://github.com/edmolo
      - icon: osf
        href: https://osf.io/eacnh
      - icon: linkedin
        href: https://www.linkedin.com/in/logan-s-edmondson/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



